### ISSUE TITLE
Cloud Backup issues

### ISSUE THREAD

**Issue by alccis** [Alexr03/TCAdminBackup#1]
First issue what i got:
when the module is installed it is installed correctly and the Backup Administrator icon appears in the settings, the Backup section also appears in the file manager, but when you try to press the Backup Administration icon in the settings, an error page appears. 

Second issue what i got:
When the module tries to be deleted, it deletes the files from the Cloud backup folder but the folder remains, Similarly the data in the Database about this installed module remains, Also the site claims that the module is still installed and can only be tried to delete again, that Backup Administrator icon will also be left in the settings, 
that is, the module cannot be removed correctly.

**Comment by Alexr03** [comment]
@alccis Hi - Can you please do as the screenshot says and enable custom errors to show remotely, or login to the master server itself and navigate to http://localhost/BackupAdmin - Ensure you are logged in before doing this. Get back to me with the screenshot of the full error.

**Comment by Alexr03** [comment]
Was bug with plugin repository itself - Has now been fixed.
