### ISSUE TITLE
Can't change S3 region

### ISSUE THREAD

**Issue by revij** [Alexr03/TCAdminBackup#6]
A bit confused as to how one can set the region for S3 backups as when you create a fileserver there are no custom fields you can set.
```
_region = fileServer.CustomFields["S3:REGION"] != null
                ? fileServer.CustomFields["S3:REGION"].ToString()
                : "us-east-1";
```
In this case, wouldn't it be better to retrieve this from the FileServer's name?
[S3-Fra1] as an example - unless of course there is a way to set a "S3:REGION" custom field for a fileserver.

**Comment by Alexr03** [comment]
Hi @revij 
I agree, I didn't really think about this at the time. 
FileServers do have CustomFields but they are different than what you are thinking of. 

I will work on a separate module that will allow CustomFields to be easily changed on these type of objects.

If you feel advanced, you can edit the TCAdmin database in the tc_file_servers table, find the correct row and edit the app_data field. Add this line:
```
<add key="S3:REGION" value="us-east-1" type="System.String,mscorlib" />
```
and change the value as required.

**Comment by Alexr03** [comment]
I have released another module on the plugin repository called Custom Fields Editor.
Install that on TCAdmin and goto your File Server and click the button.

Add a new record where:
Key is "**S3:REGION**"
Value is "**The S3 region**"

That should do what you need.

**Comment by Alexr03** [comment]
Closing. Anything else, open another issue.
